# name: Run every 5 minute

# on:
#   schedule:
#   - cron: "*/5 * * * *"

# jobs:
#   cron:
#     name: Run every 5 minutes
#     runs-on: ubuntu-latest

#     steps:
#       - name: Hello world
#         run: echo "Hello world"

name: Do Nothing Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step that does nothing
        run: echo "This workflow intentionally does nothing."
