name: Secrets workflow

on:
  pull_request:
    branches: ["main"]


env:
  API_CSPROJ_PATH: "./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"

permissions: {}

jobs:
  secrets:
    name: Secrets Demo
    runs-on: ubuntu-latest

<<<<<<< HEAD
    steps:
      - name: echo enviroment variables
        run: echo "$API_CSPROJ_PATH"
=======
    env:
      JOB_NAME: "secrets"

    steps:
      - name: echo enviroment variables
        run: echo "The value of ${{ secrets.SECRET_API_KEY }} is $API_CSPROJ_PATH"
>>>>>>> 445642dc09c40eb3b3226381a2f30edb2ea6c99d
