name: Secrets workflow

on:
  pull_request:
    branches: ["main"]


env:
  API_CSPROJ_PATH: "./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"

permissions: {}

jobs:
  secrets:
    name: Secrets Demo
    runs-on: ubuntu-latest

    steps:
      - name: echo enviroment variables
        run: echo "$API_CSPROJ_PATH"
